# Generated by Django 4.0.4 on 2022-07-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0004_alter_contenido_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Contenido')),
                ('uploadedFile', models.FileField(blank=True, null=True, upload_to='Contenido/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('cintent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.contenido', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'contenido',
                'verbose_name_plural': 'contenidos',
                'ordering': ['name'],
            },
        ),
    ]
