# Generated by Django 4.0.4 on 2022-07-13 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_alter_contenido_material'),
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='cintent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_posts', to='contenido.contenido', verbose_name='Autor'),
        ),
    ]
