# Generated by Django 4.0.4 on 2022-07-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_alter_documento_cintent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='cintent',
            new_name='content',
        ),
    ]
