# Generated by Django 4.0.4 on 2022-06-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='carrera',
            field=models.CharField(max_length=200, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Contenido'),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='material',
            name='silabo',
            field=models.TextField(verbose_name='Silabo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='temas',
            name='descripcion',
            field=models.TextField(verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='temas',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre Tema'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
