# Generated by Django 4.0.4 on 2022-07-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_material_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Duracion de la materia'),
        ),
        migrations.AddField(
            model_name='material',
            name='nivel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nivel de la materia'),
        ),
    ]
