# Generated by Django 4.0.4 on 2022-06-25 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_carrera_carrera_alter_contenido_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='silabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Tema')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'silabo',
                'verbose_name_plural': 'silabos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['name'], 'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='temas',
        ),
        migrations.AlterField(
            model_name='material',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.persona', verbose_name='Autor'),
        ),
        migrations.DeleteModel(
            name='temas',
        ),
        migrations.AlterField(
            model_name='material',
            name='silabo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.silabo', verbose_name='Tema'),
        ),
    ]
