# Generated by Django 4.0.4 on 2022-07-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_material_duration_material_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='nivel',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='persona',
            new_name='person',
        ),
    ]
