# Generated by Django 4.0.4 on 2022-06-25 19:19

from django.db import migrations, models
import django.db.models.deletion
import material.models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_silabo_alter_persona_options_remove_material_temas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['title'], 'verbose_name': 'material', 'verbose_name_plural': 'materias'},
        ),
        migrations.AddField(
            model_name='contenido',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to=material.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tipo del Contenido'),
        ),
        migrations.AlterField(
            model_name='material',
            name='silabo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.silabo', verbose_name='Silabo'),
        ),
    ]
