# Generated by Django 4.0.4 on 2022-06-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_alter_material_options_contenido_uploadedfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to='filename'),
        ),
    ]
