# Generated by Django 4.0.4 on 2022-07-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_rename_descripcion_material_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(choices=[('CL', 'Clases'), ('PR', 'Practicas'), ('TR', 'Tareas'), ('LS', 'Lecciones'), ('EX', 'Examenes'), ('OT', 'Otros')], max_length=200, verbose_name='Titulo de la materia'),
        ),
    ]
