# Generated by Django 4.0.4 on 2022-07-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_alter_material_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo de la materia'),
        ),
    ]
