# Generated by Django 4.0.4 on 2022-06-28 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_alter_contenido_uploadedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['title'], 'verbose_name': 'material', 'verbose_name_plural': 'materiales'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='image',
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo de la materia'),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo del Tema')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materia', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'materiales',
                'verbose_name_plural': 'materiales',
                'ordering': ['title'],
            },
        ),
    ]
