# Generated by Django 4.0.4 on 2022-06-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_alter_material_options_remove_material_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['title'], 'verbose_name': 'tema', 'verbose_name_plural': 'temas'},
        ),
        migrations.RemoveField(
            model_name='tema',
            name='image',
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materia', verbose_name='Imagen'),
        ),
    ]
