# Generated by Django 4.0.4 on 2022-06-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_alter_tema_options_remove_tema_image_material_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='material',
        ),
        migrations.AddField(
            model_name='tema',
            name='material',
            field=models.ManyToManyField(related_name='get_posts', to='material.material', verbose_name='Contenido'),
        ),
    ]
