# Generated by Django 4.0.4 on 2022-07-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0011_remove_tema_material_tema_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='material',
            name='silabo',
        ),
        migrations.AddField(
            model_name='material',
            name='Contenido',
            field=models.ManyToManyField(related_name='get_posts', to='material.contenido', verbose_name='Contenido'),
        ),
        migrations.DeleteModel(
            name='silabo',
        ),
    ]
