# Generated by Django 4.0.4 on 2022-07-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_remove_material_contenido_remove_material_silabo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Contenido'),
        ),
        migrations.CreateModel(
            name='TemasContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tipo del Contenido')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('Contenido', models.ManyToManyField(related_name='get_posts', to='material.contenido', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'contenido',
                'verbose_name_plural': 'contenidos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='Contenido',
            field=models.ManyToManyField(related_name='get_posts', to='material.temascontenido', verbose_name='Contenido'),
        ),
    ]
