# Generated by Django 4.0.4 on 2022-07-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0013_alter_contenido_name_temascontenido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temascontenido',
            options={'ordering': ['name'], 'verbose_name': 'Tipocontenido', 'verbose_name_plural': 'Tiposcontenidos'},
        ),
    ]
