# Generated by Django 4.0.4 on 2022-07-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0015_alter_temascontenido_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temascontenido',
            name='Contenido',
            field=models.ManyToManyField(blank=True, related_name='get_posts', to='material.contenido', verbose_name='Contenido'),
        ),
    ]
