# Generated by Django 4.0.4 on 2022-07-07 18:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0017_alter_temascontenido_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='temascontenido',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
    ]
