# Generated by Django 4.0.4 on 2022-07-12 16:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tipo del Contenido')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'tipocontenido',
                'verbose_name_plural': 'tiposcontenidos',
                'ordering': ['name'],
            },
        ),
    ]
