# Generated by Django 4.0.4 on 2022-07-12 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material.material', verbose_name='Autor'),
        ),
    ]
