# Generated by Django 4.0.4 on 2022-07-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_alter_contenido_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='name',
            field=models.CharField(choices=[('CL', 'Clases'), ('PR', 'Practicas'), ('TR', 'Tareas'), ('LS', 'Lecciones'), ('EX', 'Examenes'), ('OT', 'Otros')], max_length=200, verbose_name='Tipo del Contenido'),
        ),
    ]
