# Generated by Django 4.0.4 on 2022-07-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_alter_contenido_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='name',
            field=models.CharField(choices=[('Clases', 'Clases'), ('Practicas', 'Practicas'), ('Tareas', 'Tareas'), ('Tareas', 'Lecciones'), ('Examenes', 'Examenes'), ('Otros', 'Otros')], max_length=200, verbose_name='Tipo del Contenido'),
        ),
    ]
