# Generated by Django 4.0.4 on 2022-07-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_rename_descripcion_material_description_and_more'),
        ('temas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='material',
            field=models.ManyToManyField(blank=True, related_name='tema', to='material.material', verbose_name='Material'),
        ),
    ]
