# Generated by Django 4.0.4 on 2022-07-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imge',
            field=models.ImageField(blank=True, null=True, upload_to='persona', verbose_name='Imagen Docente'),
        ),
        migrations.AddField(
            model_name='persona',
            name='mail',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Correo'),
        ),
    ]
