# Generated by Django 4.0.4 on 2022-07-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_persona_imge_persona_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='imge',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='titulo',
            new_name='title',
        ),
    ]
